# Generated by Django 5.0.3 on 2024-04-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=20)),
                ('percentage', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
