# Generated by Django 5.0.3 on 2024-04-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='Bags',
            new_name='bags',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Destination',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='FirstClass',
            new_name='firstclass',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Passenger',
            new_name='passenger',
        ),
    ]
